name: Nightly Build

on:
  push:
    branches: [master, dev]
  schedule:
#     - cron: '0 1 * * *'  # Run every day at 1 AM UTC
    - cron: '*/5 1-23 * * *'  # Run every 5 minutes from 1 AM to 11 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for code changes
        id: code_changes
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Setup flutter engine
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          
      - name: Fetch dependencies
        run: flutter packages get
      
      - name: Run tests
        run: flutter test --coverage
          
      - name: Determine code changes
        id: determine_changes
        run: |
          CHANGES_COUNT=$(git diff --name-only HEAD~1 | wc -l)
          echo "::set-output name=changes::${CHANGES_COUNT}"
          
      - name: Nightly Build
        if: ${{ steps.determine_changes.outputs.changes > 0 }}
        run: flutter build apk --debug
        working-directory: ./example
